{
 "title": "User Profile Workload",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "operation", "label": "Operation", "query": { "query": "operations_total" } }
  ]
 },
 "panels": [
  {
   "title": "Steady",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_total{operation=~\"$operation\", phase=\"Steady\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Failed operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_failed_total{job=\"spectroperf\", operation=~\"$operation\", phase=\"Steady\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "99th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"Steady\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"Steady\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    },
    {
     "title": "50th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"Steady\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"Steady\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    },
    {
     "title": "Operations Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(operations_total{operation=~\"$operation\", phase=\"Steady\"}[1m])",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "sum(rate(operations_total{operation=~\"$operation\", phase=\"Steady\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$operation duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "repeat": "operation",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "operation_duration_milliseconds_bucket{operation=\"$operation\", phase=\"Steady\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ramp Up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_total{operation=~\"$operation\", phase=\"RampUp\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Failed operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_failed_total{job=\"spectroperf\", operation=~\"$operation\", phase=\"RampUp\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "99th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampUp\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampUp\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    },
    {
     "title": "50th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampUp\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampUp\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    },
    {
     "title": "Operations Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(operations_total{operation=~\"$operation\", phase=\"RampUp\"}[1m])",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "sum(rate(operations_total{operation=~\"$operation\", phase=\"RampUp\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Ramp Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_total{operation=~\"$operation\", phase=\"RampDown\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Failed operations",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(operations_failed_total{job=\"spectroperf\", operation=~\"$operation\", phase=\"RampDown\"}[$__range])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "99th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampDown\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampDown\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    },
    {
     "title": "50th percentile operation duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampDown\"}[$__range])) by (le, operation))",
       "legendFormat": "{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(operation_duration_milliseconds_bucket{operation=~\"$operation\", phase=\"RampDown\"}[$__range])) by (le))",
       "legendFormat": "all operations"
      }
     ]
    }
   ]
  }
 ]
}