package workload

import (
	"context"
	"math/rand"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	gotel "github.com/couchbase/gocb-opentelemetry"
	"github.com/couchbase/gocb/v2"
	"github.com/couchbaselabs/spectroperf/configuration"
	"go.opentelemetry.io/otel/attribute"
	"go.uber.org/zap"
)

type localMetric struct {
	opName   string
	numUsers int
	duration time.Duration
}

// A spectroperf Workload is defined by:
//   - The documents it operates on
//   - The Operations it performs on those documents
//   - The probability matrix defining the likelihood of one operation being followed by another
type Workload interface {
	// GenerateDocument creates a random document appropriate for the workload
	GenerateDocument(id int) DocType
	// Operations returns The list of operations that a workload supports
	Operations() []string
	// Probabilities returns the probability matrix for the workload
	Probabilities() [][]float64
	// Returns a map of operations to workload functions
	Functions() map[string]func(ctx context.Context, rctx Runctx) error
	// Setup performs any workload specific setup, e.g creating indexes
	Setup() error
}

// Setup uploads the documents generated by the workload, and calls the workloads Setup function
func Setup(w Workload, logger *zap.Logger, numItemsArg int, coll *gocb.Collection) {
	numConc := 1500
	workChan := make(chan DocType, numConc)
	var wg sync.WaitGroup

	logger.Info("Inserting documents", zap.Int("number of docs", numItemsArg))
	wg.Add(numConc)
	for i := 0; i < numConc; i++ {
		go func() {
			for {
				doc, ok := <-workChan
				if !ok {
					wg.Done()
					return
				}

				_, err := coll.Upsert(doc.Name, doc.Data, nil)
				if err != nil {
					logger.Error("data load upsert failed", zap.Error(err))
				}
			}
		}()
	}

	// Create a random document using the given workload definition
	for i := 0; i < numItemsArg; i++ {
		workChan <- w.GenerateDocument(i)
	}

	close(workChan)
	wg.Wait()

	// Call the workload's own Setup function to perform any workload specific setup
	err := w.Setup()
	if err != nil {
		logger.Fatal("failed to setup workload", zap.Error(err))
	}
}

func Run(
	w Workload,
	logger *zap.Logger,
	config *configuration.ExecutionConfig,
	markovChain [][]float64,
	tracer *gotel.OpenTelemetryRequestTracer,
) {
	logger.Info("Running workload…\n")

	sigCh := make(chan os.Signal, 10)
	ctx, cancelFn := context.WithCancel(context.Background())

	go func() {
		<-sigCh
		cancelFn()
	}()

	// Signal handler for SIGTERM
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)

	maxUsers := 0
	for _, numUsers := range config.NumUsers {
		if numUsers > maxUsers {
			maxUsers = numUsers
		}
	}

	// Create a buffered channel to send metrics from workers to a single consumer.
	metricChan := make(chan localMetric, maxUsers)

	var metricsWg sync.WaitGroup
	metricsWg.Add(1)
	go func() {
		defer metricsWg.Done()
		for metric := range metricChan {
			err := localHistograms[metric.opName][metric.numUsers].RecordValue(metric.duration.Microseconds())
			if err != nil {
				logger.Warn("failed to record value in local histogram", zap.String("operation", metric.opName), zap.Int("numUsers", metric.numUsers), zap.Error(err))
			}
		}
	}()

	for _, nextUserCount := range config.NumUsers {
		logger.Info("Starting run", zap.Int("users", nextUserCount), zap.String("duration", config.RunTime.String()))

		var wg sync.WaitGroup
		wg.Add(nextUserCount)
		for i := 0; i < nextUserCount; i++ {
			go runLoop(ctx, logger, w, config, markovChain, i, &wg, tracer, nextUserCount, metricChan)
		}
		wg.Wait()

		if ctx.Err() != nil {
			logger.Info("Run interrupted by signal, stopping", zap.Int("users", nextUserCount))
			break
		}
	}

	close(metricChan)
	metricsWg.Wait() // Ensure all metrics are processed
	cancelFn()       // Cancel the context to clean up any remaining goroutines
}

func runLoop(
	ctx context.Context,
	logger *zap.Logger,
	workload Workload,
	config *configuration.ExecutionConfig,
	markovChain [][]float64,
	runnerId int,
	wg *sync.WaitGroup,
	tracer *gotel.OpenTelemetryRequestTracer,
	numUsers int,
	metricChan chan<- localMetric,
) {
	var (
		currOpIndex   = 0 // Current operation index
		probabilities = markovChain
		functions     = workload.Functions()
		operations    = workload.Operations()
	)

	rng := rand.NewSource(int64(RandSeed + runnerId))
	r := rand.New(rng)

	timeout := time.After(config.RunTime)

	logger.Debug("Starting runner", zap.Int("runnerId", runnerId))
	runStart := time.Now()
	runEnd := runStart.Add(config.RunTime)

	var runCtx Runctx
	runCtx.r = *r
	runCtx.l = *logger
	// todo: move this into context.value, a KV store for junk

	for {
		select {
		case <-ctx.Done():
			logger.Debug("Received cancel, stopping runner", zap.Int("runnerId", runnerId))
			wg.Done()
			return
		case <-timeout:
			// This case is only active for fixed-user runs
			logger.Debug("Run time reached, stopping runner", zap.Int("runnerId", runnerId))
			wg.Done()
			return
		default:
			// Get the next operation index based on probabilities
			nextOpIndex := getNextOperation(currOpIndex, probabilities, r)
			// call the next function
			nextFunction := operations[nextOpIndex]
			logger.Debug("next operation", zap.String("operation", nextFunction))

			var t time.Duration
			if config.Sleep == 0 {
				// sleep a random amount of time up to 5 seconds
				t = time.Duration(r.Int31n(5000-400)+400) * time.Millisecond
			} else {
				t = config.Sleep
			}
			time.Sleep(t)

			phase := MetricState(runStart, runEnd, config.RampTime)
			attemptMetrics[nextFunction][phase][numUsers].Inc()

			ctx2, span := tracer.Wrapped().Start(ctx, nextFunction)
			span.SetAttributes(attribute.Key("workload-phase").String(string(phase)))

			start := time.Now()
			err := functions[operations[nextOpIndex]](ctx2, runCtx)
			duration := time.Now().Sub(start)
			if err != nil {
				logger.Error("operation failed", zap.String("operation", nextFunction), zap.Error(err))
				failedMetrics[nextFunction][phase][numUsers].Inc()
				if phase == Steady {
					localFailedCounters[nextFunction][numUsers].Add(1)
				}
			} else {
				// Only record duration metrics for successful operations
				durationMetrics[nextFunction][phase][numUsers].Observe(float64(duration.Microseconds()) / 1000)
				if phase == Steady {
					select {
					case metricChan <- localMetric{opName: nextFunction, duration: duration, numUsers: numUsers}:
					default:
						logger.Warn("metric channel is full, dropping metric", zap.Int("numUsers", numUsers))
					}
				}
			}

			// update for next time
			currOpIndex = nextOpIndex
			span.End()
		}
	}
}

func getNextOperation(currOpIndex int, probabilities [][]float64, r *rand.Rand) int {
	// Get the probabilities for the current operation
	probRow := probabilities[currOpIndex]

	// Calculate a random value between 0 and the total probability (which should sum to 1)
	randVal := r.Float64()

	// Iterate through the probability row to select the next operation
	var cumulativeProb float64
	for i, prob := range probRow {
		cumulativeProb += prob
		if randVal < cumulativeProb {
			return i
		}
	}

	// Fallback: return the last operation if something goes wrong
	return len(probRow) - 1
}
